# 会社用（デフォルト）
Host github.com
	HostName github.com
	User git
	IdentityFile ~/.ssh/github-work.pub
	IdentitiesOnly yes

# プライベート用
Host github-personal
	HostName github.com
	User git
	IdentityFile ~/.ssh/github-personal.pub
	IdentitiesOnly yes
